# Generated by Django 6.0.2 on 2026-03-04 03:42

import django
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('produtos', models.ManyToManyField(related_name='pedidos', to='produto.produto', verbose_name='Produtos')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do Pedido')),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Frete')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONFIRMADO', 'Confirmado'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status do Pedido')),
            ],
        ),
    ]
