# Generated by Django 6.0.2 on 2026-03-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('produto', '0002_ebook_livro_remove_produto_tipo_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='produto.produto', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do Pedido')),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Frete')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONFIRMADO', 'Confirmado'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status do Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cliente.cliente', verbose_name='Cliente')),
                ('produtos', models.ManyToManyField(related_name='pedidos', through='pedido.ItemPedido', to='produto.produto', verbose_name='Produtos')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto')},
        ),
    ]
