# Generated by Django 6.0.2 on 2026-03-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
    ]
