# Generated by Django 6.0.2 on 2026-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data do Pedido'),
        ),
    ]
