# Generated by Django 6.0.2 on 2026-03-04 03:42

import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('ano_lancamento', models.IntegerField(verbose_name='Ano de lançamento')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('tipo_produto', models.CharField(choices=[('LIVRO', 'Livro'), ('EBOOK', 'E-book')], max_length=20, verbose_name='Tipo do produto')),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('OT', 'Outro')], max_length=2, verbose_name='Idioma')),
                ('categorias', models.ManyToManyField(blank=True, related_name='produtos', to='produto.categoria', verbose_name='Categorias')),
            ],
        ),
    ]
