# Generated by Django 6.0.2 on 2026-03-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('arquivo', models.FileField(upload_to='ebooks/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'E-book',
                'verbose_name_plural': 'E-books',
            },
            bases=('produto.produto',),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
            bases=('produto.produto',),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedor.vendedor', verbose_name='Vendedor'),
        ),
    ]
