# Generated by Django 6.0.2 on 2026-03-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_ebook_livro_remove_produto_tipo_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
