# Generated by Django 6.0.2 on 2026-03-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='endereco',
        ),
    ]
